### ISSUE TITLE
`pick()` got an unexpected keyword argument `options_map_func`

### ISSUE THREAD

**Issue by japplefield** [eecs485staff/agio-cli#39]
Looks like that option has been removed in `pick==2.0.0`:

```console
(env) jmapple@Justins-MacBook-Pro agio-cli % ./env/bin/agio groups --queue
Traceback (most recent call last):
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/./env/bin/agio", line 33, in <module>
    sys.exit(load_entry_point('agiocli', 'console_scripts', 'agio')())
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/env/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/agiocli/__main__.py", line 189, in groups
    project = utils.get_project_smart(project_arg, course_arg, client)
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/agiocli/utils.py", line 377, in get_project_smart
    course = get_course_smart(course_arg, client)
  File "/Users/jmapple/Developer/eecs485-staff/agio-cli/agiocli/utils.py", line 235, in get_course_smart
    selected_courses = pick.pick(
TypeError: pick() got an unexpected keyword argument 'options_map_func'
(env) jmapple@Justins-MacBook-Pro agio-cli % code .
(env) jmapple@Justins-MacBook-Pro agio-cli % pip freeze
-e git+https://github.com/eecs485staff/agio-cli@5b241b68e9bba91d38012f3aa789d79a71012e8f#egg=agiocli
certifi==2022.9.14
charset-normalizer==2.1.1
click==8.1.3
idna==3.4
pick==2.0.0
python-dateutil==2.8.2
requests==2.28.1
six==1.16.0
urllib3==1.26.12
(env) jmapple@Justins-MacBook-Pro agio-cli % pip install pick==1.6.0
Collecting pick==1.6.0
  Downloading pick-1.6.0-py3-none-any.whl (5.5 kB)
Installing collected packages: pick
  Attempting uninstall: pick
    Found existing installation: pick 2.0.0
    Uninstalling pick-2.0.0:
      Successfully uninstalled pick-2.0.0
Successfully installed pick-1.6.0
WARNING: There was an error checking the latest version of pip.
(env) jmapple@Justins-MacBook-Pro agio-cli % ./env/bin/agio groups --queue
# it works
```

**Comment by japplefield** [comment]
Closed by #40
